# Site
name: "VPN Fact Check"
title: "Side blog of vpnfactcheck.com"
description: "Deep dive into the VPN world"
logo: 'assets/images/VPN_FACTCHECK-removebg-80.png'
favicon: 'assets/images/logo.png'
baseurl: /vpnfactcheck
google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'vpnfactcheck'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: vpnfactcheck@gmail.com

# Authors
authors:

  karson33:
    name: karson33
    display_name: Karson33
    gravatar: 623c471df65921b37ebe8e8b7db695a8
    email: vpnfactcheck@gmail.com
    web: https://vpnfactcheck.com
    twitter: https://twitter.com/vpnfactcheck
    description: "VPN testing enthusiastic - ask me to test anything about VPN"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
